
create table Bet (betId bigint generated by default as identity, betDate timestamp, betPrice decimal(19,2), betState integer, lot_id bigint, user_id bigint, primary key (betId));

create table Earnings (earningsId bigint generated by default as identity, payment decimal(19,2), paymentDate timestamp, USER_ID bigint, primary key (earningsId));

create table Lot (lotId bigint generated by default as identity, description varchar(255), endDate timestamp, imgPath varchar(255), lotState integer, name varchar(255), startPrice decimal(19,2), CURRENTBET_ID bigint, user_id bigint, primary key (lotId));

create table User (userId bigint generated by default as identity, balance decimal(19,2), birthday timestamp, discount decimal(19,2), email varchar(255), experience integer not null, lastBetDate timestamp, name varchar(255), password varchar(255), points decimal(19,2), role varchar(255), userRole integer, primary key (userId));

alter table Bet add constraint FK104718222BD11 foreign key (lot_id) references Lot;
alter table Bet add constraint FK10471A4599FC3 foreign key (user_id) references User;
alter table Earnings add constraint FKD3B580C9A4599FC3 foreign key (USER_ID) references User;
alter table Lot add constraint FK12B31620133CA foreign key (CURRENTBET_ID) references Bet;
alter table Lot add constraint FK12B31A4599FC3 foreign key (user_id) references User;